hoverboard_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
  left_wheel  : "left_wheel"
  right_wheel : "right_wheel"

hoverboard_velocity_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : "left_wheel"
  right_wheel : "right_wheel"
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  publish_rate: 50.0               # default: 50
  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5

  # Base frame_id
  base_frame_id: base_footprint #default: base_link

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true # default false
      max_velocity           : 2.0  # m/s
      min_velocity           : -0.5  # m/s
      has_acceleration_limits: true # default false
      max_acceleration       : 0.8  # m/s^2
      has_jerk_limits        : false  # default false
      max_jerk               : 0.0  # m/s^3
  angular:
    z:
      has_velocity_limits    : true # default false
      max_velocity           : 3.14  # rad/s
      min_velocity           : -3.14  # rad/s
      has_acceleration_limits: true # default false
      max_acceleration       : 3.14  # rad/s^2
      has_jerk_limits        : false # default false
      max_jerk               : 0.0  # rad/s^3

  enable_odom_tf: false # default true
  wheel_separation : 0.34
  wheel_radius : 0.0825
  odom_frame_id: "/odom"  # default: "/odom"
  publish_cmd: false  # default false
  allow_multiple_cmd_vel_publishers: true
  velocity_rolling_window_size: 10  # default 10