!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  blob_filter_by_area: true
  blob_filter_by_circularity: true
  blob_filter_by_convexity: true
  blob_filter_by_inertia: false
  blob_max_area: 2800.0
  blob_max_circularity: 1.0
  blob_max_convexity: 1.0
  blob_max_inertia: 1.0
  blob_min_area: 100.0
  blob_min_circularity: 0.42
  blob_min_convexity: 0.0
  blob_min_inertia: 0.27
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      blob_filter_by_area: true
      blob_filter_by_circularity: true
      blob_filter_by_convexity: true
      blob_filter_by_inertia: false
      blob_max_area: 2800.0
      blob_max_circularity: 1.0
      blob_max_convexity: 1.0
      blob_max_inertia: 1.0
      blob_min_area: 100.0
      blob_min_circularity: 0.42
      blob_min_convexity: 0.0
      blob_min_inertia: 0.27
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      outline_scale_factor: 30
      p_bot_left_x: 100
      p_bot_left_y: 520
      p_bot_right_x: 600
      p_bot_right_y: 480
      p_top_left_x: 220
      p_top_left_y: 180
      p_top_right_x: 460
      p_top_right_y: 180
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      pattern: 2
      pattern_delta_x: 0.08
      pattern_delta_y: 0.08
      pattern_offset_x: 1.15
      pattern_offset_y: 0.0
      points_per_col: 15
      points_per_row: 4
      state: true
      type: ''
    state: []
  outline_scale_factor: 30
  p_bot_left_x: 100
  p_bot_left_y: 520
  p_bot_right_x: 600
  p_bot_right_y: 480
  p_top_left_x: 220
  p_top_left_y: 180
  p_top_right_x: 460
  p_top_right_y: 180
  pattern: 2
  pattern_delta_x: 0.08
  pattern_delta_y: 0.08
  pattern_offset_x: 1.15
  pattern_offset_y: 0.0
  points_per_col: 15
  points_per_row: 4
state: []
