play_motion:
  motions:
    look_down:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0.0, -0.6]
        time_from_start: 1.0
    torso_up:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.32, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 2.0


