%YAML:1.0
---
# width and height of the original image in pixels
image_height: 480
image_width: 640

# width and height in pixels of segmentation network output
# (when given the above input)
#seg_height: 11
#seg_width: 54
seg_height: 960 #480
seg_width: 1280 #640

# the width and height of the image representing a top-down view of the real world
costmap_height: 480 # 480
costmap_width: 960 # 640

# the number of meters per pixel (currently 0.05)
#m_per_pixel: 5.00e-02

#m_per_pixel: 0.0067
m_per_pixel: 0.0006

#m_per_pixel: 0.01
#m_per_pixel: 0.01

# file path indicating where to write the file
homography_file_path: "/home/alex/src/catkin_ws/src/robaka-ros/conf/semantic-segmentation/homography4.xml"

# file path pointing to sample segmentation data
seg_data_path: "/home/alex/segmentation.png"
