global_frame: map
rolling_window: true
width: 16
height: 16

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_l,                 type: "costmap_2d::InflationLayer"}
